version: '3'

services:
  app:
    build: .
    command:
    environment:
      NODE_ENV:
    networks:
      - app-network
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
